vcpkg_from_github(
    OUT_SOURCE_PATH SOURCE_PATH
    REPO sweemer/quickfix
    REF 42e853ba526cc2143b6cab55ce5d9c20b5967745
    SHA512 3862a40324697fcf11c64d8e256ebb3d7da3334c6b08ef311d5c85820390f87c261f37d8cf38bc3899598f9b780afb88037fa1e0eea057cd09c3f9fe2be6a2f5
    HEAD_REF master
)

string(COMPARE EQUAL "${VCPKG_LIBRARY_LINKAGE}" "dynamic" QUICKFIX_SHARED_LIBS)

vcpkg_cmake_configure(
    SOURCE_PATH "${SOURCE_PATH}"
    DISABLE_PARALLEL_CONFIGURE
    OPTIONS
        -DQUICKFIX_SHARED_LIBS=${QUICKFIX_SHARED_LIBS}
        -DQUICKFIX_EXAMPLES=OFF
        -DQUICKFIX_TESTS=OFF
        -DHAVE_MYSQL=OFF
        -DHAVE_ODBC=OFF
        -DHAVE_POSTGRESQL=OFF
        -DHAVE_PYTHON3=OFF
        -DHAVE_SSL=ON
)

vcpkg_cmake_install()
vcpkg_copy_pdbs()
vcpkg_cmake_config_fixup(CONFIG_PATH share/cmake/quickfix)

file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/include")
file(REMOVE_RECURSE "${CURRENT_PACKAGES_DIR}/debug/share")

file(COPY "${CMAKE_CURRENT_LIST_DIR}/usage" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}")
file(INSTALL "${SOURCE_PATH}/LICENSE" DESTINATION "${CURRENT_PACKAGES_DIR}/share/${PORT}" RENAME copyright)
